# frozen_string_literal: true

require_relative "../test_helper"

class ShaderBuilderCoreTest < Test::Unit::TestCase
  test "initializes with name" do
    builder = RLSL::ShaderBuilder.new(:test)
    assert_equal "test", builder.name
  end

  test "uniforms block defines uniforms" do
    builder = RLSL::ShaderBuilder.new(:test)
    builder.uniforms do
      float :time
      vec2 :mouse
    end
    uniforms = builder.uniforms
    assert_equal :float, uniforms[:time]
    assert_equal :vec2, uniforms[:mouse]
  end

  test "helpers block is stored" do
    builder = RLSL::ShaderBuilder.new(:test)
    builder.helpers(:c) { "// Helper code" }
  end

  test "fragment block is stored" do
    builder = RLSL::ShaderBuilder.new(:test)
    builder.fragment { "return vec3_new(1.0, 0.0, 0.0);" }
  end

  test "build_metal_shader creates MSL::Shader" do
    builder = RLSL::ShaderBuilder.new(:test_metal)
    builder.uniforms { float :time }
    builder.helpers(:c) { "" }
    builder.fragment { "return float3(1.0, 0.0, 0.0);" }

    shader = builder.build_metal_shader
    assert_kind_of RLSL::MSL::Shader, shader
  end

  test "build_wgsl_shader returns WGSL source" do
    builder = RLSL::ShaderBuilder.new(:test_wgsl)
    builder.uniforms { float :time }
    builder.fragment_source("|frag_coord, resolution, u|\nvec3(1.0, 0.0, 0.0)")

    wgsl = builder.build_wgsl_shader
    assert_kind_of String, wgsl
    assert wgsl.include?("@compute")
  end

  test "build_glsl_shader returns GLSL source" do
    builder = RLSL::ShaderBuilder.new(:test_glsl)
    builder.uniforms { float :time }
    builder.helpers(:c) { "" }
    builder.fragment { "return vec3_new(1.0, 0.0, 0.0);" }

    glsl = builder.build_glsl_shader
    assert_kind_of String, glsl
    assert glsl.include?("#version 450")
  end

  test "generated target sources include the shader name" do
    builder = RLSL::ShaderBuilder.new(:named_shader)
    builder.fragment_source("|frag_coord, resolution, u|\nvec3(1.0, 0.0, 0.0)")

    assert_include builder.build_glsl_shader, "// GLSL shader generated by RLSL: named_shader"
    assert_include builder.build_wgsl_shader, "// WGSL shader generated by RLSL: named_shader"
    assert_include builder.build_metal_shader.msl_source, "// MSL shader generated by RLSL: named_shader"
  end

  test "native extension compiler hashes artifacts without missing digest" do
    compiler = RLSL::ShaderBuilder::NativeExtensionCompiler.new(:test_shader)

    artifact = compiler.send(:artifact_for, "void test(void) {}")

    assert_match(/^test_shader_[0-9a-f]{16}$/, artifact.ext_name)
    assert_include artifact.file, "#{artifact.ext_name}."
  end

  test "memoizes the build service until the definition changes" do
    builder = RLSL::ShaderBuilder.new(:memoized)
    first = builder.send(:build_service)

    assert_same first, builder.send(:build_service)

    builder.fragment_source("vec3(1.0)")
    assert_not_same first, builder.send(:build_service)
  end

  test "native extension identity includes the code hash" do
    compiler = RLSL::ShaderBuilder::NativeExtensionCompiler.new(:same_name)
    first = compiler.extension_name_for("first")
    second = compiler.extension_name_for("second")

    assert_match(/^same_name_[0-9a-f]{16}$/, first)
    assert_not_equal first, second
  end

  test "build_wgsl_shader rejects legacy C fragments" do
    builder = RLSL::ShaderBuilder.new(:legacy_wgsl)
    builder.fragment(:c) { "return vec3_new(1.0, 0.0, 0.0);" }

    assert_raise(RLSL::TranslationError) { builder.build_wgsl_shader }
  end
end
